"""
Student Name:
Student ID:
Student Email:
"""


#palindrome detection using a vanilla RNN with an embedding layer
#dataset generated by creating random palindromic strings 
import torch
import random
import torch.nn as nn 
import matplotlib.pyplot as plt

digits = "0123456789"

# generate a valid number string of given length
def generate_number(length):
    if length == 1:
        return random.choice(digits)
    else:
        first = random.choice("123456789")   # no leading zero
        rest = ''.join(random.choices(digits, k=length-1))
        return first + rest

# generate palindrome
def generate_palindrome(length):
    if length == 1:
        return random.choice(digits)

    half_length = length // 2

    # first digit cannot be zero if multi digit
    first_half = random.choice("123456789")
    if half_length > 1:
        first_half += ''.join(random.choices(digits, k=half_length-1))

    if length % 2 == 1:
        middle = random.choice(digits)
        palindrome = first_half + middle + first_half[::-1]
    else:
        palindrome = first_half + first_half[::-1]

    return palindrome

# generate non-palindrome
def generate_non_palindrome(length):
    # ensure length >= 2 (since length 1 is always palindrome)
    if length == 1:
        length = random.randint(2, 7)

    non_palindrome = generate_number(length)

    while non_palindrome == non_palindrome[::-1]:
        non_palindrome = generate_number(length)

    return non_palindrome

# build dataset
def build_dataset(num_examples):
    data = []

    half = num_examples // 2

    # positive examples
    for _ in range(half):
        length = random.randint(1, 7)
        num = generate_palindrome(length)
        data.append((num, 1))

    # negative examples
    for _ in range(half):
        length = random.randint(2, 7)  # avoid length 1
        num = generate_non_palindrome(length)
        data.append((num, 0))

    random.shuffle(data)
    return data

#quick test 
#dataset = build_dataset(10)
#for x in dataset:
 #   print(x)

#encoding 

#find index postion 
def digitToIndex(num):
    return digits.index(num)

#convert 
def numToTensor(num):
    tensor = torch.zeros(len(num), dtype=torch.long)
    for i, char in enumerate(num):
        tensor[i] = digitToIndex(char)
    return tensor

# convert label to tensor
def labelToTensor(label):
    return torch.tensor([label], dtype=torch.long)

# test 
#print(numToTensor("13531"))


# vanilla RNN class
class RNN(nn.Module):
    # constructor
    def __init__(self, vocab_size, embedding_size, hidden_size, output_size):
        super().__init__()
        self.hidden_size = hidden_size

        # embedding layer
        self.embedding = nn.Embedding(vocab_size, embedding_size)

        self.i2h = nn.Linear(embedding_size + hidden_size, hidden_size)
        self.h2o = nn.Linear(hidden_size, output_size)

        self.softmax = nn.LogSoftmax(dim=1)

    # forward pass
    def forward(self, input, hidden):
        # input is a digit index so embed it - note to self
        embedded = self.embedding(input)           # shape: (1, embedding_size)

        # combine embedded input with hidden state
        combined = torch.cat((embedded, hidden), 1)

        # compute next hidden state
        hidden = self.i2h(combined)

        # compute output
        output = self.h2o(hidden)
        output = self.softmax(output)

        return output, hidden

    # initialize hidden state
    def initHidden(self):
        return torch.zeros(1, self.hidden_size)


# hyperparameters
vocab_size = 10        # digits 0–9
embedding_size = 8     # small vector size
hidden_size = 128
output_size = 2        # palindrome or not

# create new model each time 
def create_model():
    return RNN(vocab_size, embedding_size, hidden_size, output_size)

#training 
learning_rate = 0.005
criterion = nn.NLLLoss()

def train(model, category_tensor, line_tensor):
    hidden = model.initHidden()
    model.zero_grad()

    # go through the digits one at a time
    for i in range(line_tensor.size()[0]):
        output, hidden = model(line_tensor[i].unsqueeze(0), hidden)

    # compare final output to true label
    loss = criterion(output, category_tensor)
    loss.backward()

    # manual SGD update
    for p in model.parameters():
        p.data.add_(p.grad.data, alpha=-learning_rate)

    return output, loss.item()


#Evaluation 
# turn into class 0 or 1 
def categoryFromOutput(output):
    top_n, top_i = output.topk(1)
    return top_i.item()

#evalute example 
def evaluate(model, line_tensor):
    hidden = model.initHidden()
    with torch.no_grad():
        for i in range(line_tensor.size()[0]):
            output, hidden = model(line_tensor[i].unsqueeze(0), hidden)

    return output

#accuracy on dataset
def test_accuracy(model, dataset):
    correct = 0

    for num, label in dataset:
        line_tensor = numToTensor(num)
        output = evaluate(model, line_tensor)
        prediction = categoryFromOutput(output)

        if prediction == label:
            correct += 1

    return correct / len(dataset)

#outer training loop
def train_model(num_examples, epochs):
    model = create_model()                     
    train_data = build_dataset(num_examples)    
    test_data = build_dataset(1000)             # for readme

    losses = []                                 
    print(f"\nTraining model with {num_examples} examples")

    for epoch in range(1, epochs + 1):
        total_loss = 0

        random.shuffle(train_data)

        for num, label in train_data:
            line_tensor = numToTensor(num)
            category_tensor = labelToTensor(label)
            output, loss = train(model, category_tensor, line_tensor)
            total_loss += loss

        avg_loss = total_loss / len(train_data)
        losses.append(avg_loss)

        # print progress every few epochs
        if epoch % 5 == 0 or epoch == 1:
            train_acc = test_accuracy(model, train_data)
            test_acc = test_accuracy(model, test_data)
            print(f"Epoch {epoch}/{epochs} | Loss: {avg_loss:.4f} | Train Acc: {train_acc:.4f} | Test Acc: {test_acc:.4f}")

    return model, losses, test_data            

# save loss figure 
def save_loss_plot(losses, filename, title):
    plt.figure()
    plt.plot(losses)
    plt.xlabel("Epoch")
    plt.ylabel("Average Loss")
    plt.title(title)
    plt.savefig(filename)
    plt.close()

# save the model 
def save_model(model, filename):
    torch.save(model.state_dict(), filename)

# load trained model 
def load_model(filename):
    model = create_model()
    model.load_state_dict(torch.load(filename))
    model.eval()
    return model
#load the csv 
def load_csv(filename):
    data = []
    with open(filename, "r") as f:
        for line in f:
            num, label = line.strip().split(",")
            data.append((num, int(label)))
    return data
# for csv 
def run_on_csv(model_filename, csv_filename):
    model = load_model(model_filename)
    csv_data = load_csv(csv_filename)
    acc = test_accuracy(model, csv_data)
    print(f"{model_filename} accuracy on {csv_filename}: {acc:.4f}")
    
#train all 3  models
model_200, losses_200, own_test_200 = train_model(200, 30)
save_model(model_200, "model_200.pth")
save_loss_plot(losses_200, "loss_200.png", "Training Loss (200 examples)")
print("Own test accuracy for model_200:", test_accuracy(model_200, own_test_200))

model_1000, losses_1000, own_test_1000 = train_model(1000, 30)
save_model(model_1000, "model_1000.pth")
save_loss_plot(losses_1000, "loss_1000.png", "Training Loss (1000 examples)")
print("Own test accuracy for model_1000:", test_accuracy(model_1000, own_test_1000))

model_50000, losses_50000, own_test_50000 = train_model(50000, 10)  # CHANGED: fewer epochs because dataset is large
save_model(model_50000, "model_50000.pth")
save_loss_plot(losses_50000, "loss_50000.png", "Training Loss (50000 examples)")
print("Own test accuracy for model_50000:", test_accuracy(model_50000, own_test_50000))

# make sure test.csv is in the same folder
run_on_csv("model_200.pth", "test.csv")
run_on_csv("model_1000.pth", "test.csv")
run_on_csv("model_50000.pth", "test.csv")