
#palindrome detection using RNNs
#dataset generated by creating random palindromic strings 
import torch.nn as nn 
import torch
import random

digits = "0123456789"

# generate a valid number string of given length
def generate_number(length):
    if length == 1:
        return random.choice(digits)
    else:
        first = random.choice("123456789")   # no leading zero
        rest = ''.join(random.choices(digits, k=length-1))
        return first + rest

# generate palindrome
def generate_palindrome(length):
    if length == 1:
        return random.choice(digits)

    half_length = length // 2

    # first digit cannot be zero if multi digit
    first_half = random.choice("123456789")
    if half_length > 1:
        first_half += ''.join(random.choices(digits, k=half_length-1))

    if length % 2 == 1:
        middle = random.choice(digits)
        palindrome = first_half + middle + first_half[::-1]
    else:
        palindrome = first_half + first_half[::-1]

    return palindrome

# generate non-palindrome
def generate_non_palindrome(length):
    # ensure length >= 2 (since length 1 is always palindrome)
    if length == 1:
        length = random.randint(2, 7)

    non_palindrome = generate_number(length)

    while non_palindrome == non_palindrome[::-1]:
        non_palindrome = generate_number(length)

    return non_palindrome

# build dataset
def build_dataset(num_examples):
    data = []

    half = num_examples // 2

    # positive examples
    for _ in range(half):
        length = random.randint(1, 7)
        num = generate_palindrome(length)
        data.append((num, 1))

    # negative examples
    for _ in range(half):
        length = random.randint(2, 7)  # avoid length 1
        num = generate_non_palindrome(length)
        data.append((num, 0))

    random.shuffle(data)
    return data

#quick test 
#dataset = build_dataset(10)
#for x in dataset:
 #   print(x)

#encoding 

def encode_string(s):
    # create a 10-dimensional one-hot vector for each digit
    encoding = []
    for char in s:
        vector = [0] * 10
        if char in digits:
            index = digits.index(char)
            vector[index] = 1
        encoding.append(vector)
    return torch.tensor(encoding, dtype=torch.float)



#
# vanilla RNN class
#class RNN(nn.Module):
    #constructor method to initialize the RNN
#    def _init_(self,input_size,hidden_size,output_size):
#        super(RNN,self)._init_()
#        self.hidden_size = hidden_size
 #       self.i2h = nn.Linear(input_size + hidden_size, hidden_size)
 #       self.h2o = nn.Linear(hidden_size, output_size)
 #       self.softmax = nn.LogSoftmax(dim=1)
    #forward method to define the forward pass of the RNN
#    def forward(self,input,hidden):
#        combined = torch.cat((input,hidden),1)
#        hidden = self.i2h(combined)
#        output = self.h2o(hidden)
#        output = self.softmax(output)

        #return output and and new hidden state 
 #       return output, hidden
    #method to initialize the hidden state of the RNN
#    def initHidden(self):
#        return torch.zeros(1,self.hidden_size)
    
# hidden layer size to 128 neurons
#n_hidden = 128

#create an instance of the RNN with: 
#rnn = RNN(n_letters, n_hidden, n_categories)

#training 


#Evaluation 